### ISSUE TITLE
Update to v1.8.17 broke the extension on Firefox

### ISSUE THREAD

**Issue by DeanAyalon** [material-extensions/material-icons-browser-extension#107]
Using Firefox on two machines: MacOS Ventura 13.6.7 and Manjaro 24.0.3 Wynsdey

Browsers are synced using Mozilla account, both worked before the update

After update, I am not sure whether the icons were not working right away, I was reading through the updates and saw that I cannot see any new icons on the releases page, so I disabled and re-enabled the extension - That's when it stopped working completely, the icons went back to plain old GitHub.

The extension has been given authorization to all websites.
Changing settings, clearing cache, signing out of Mozilla, and restarting the extension, or Firefox, did not work.

I tried removing and installing it again, but it did not help. 
Furthermore, that is when I checked my Linux, and for some reason, though the extension was installed again, it was no longer installed on the Linux. Re-installing it there also did nothing.

Restarting the computers themselves also did not work

Tried installing it on Chrome, and though it works, seems the Chrome Web Store still uses v1.8.15

I want to check if the version is problematic, or if the error lies elsewhere, but do not know how to install the extension from the zip file provided in the releases page. Please, forgive my ignorance, but how do I achieve that?

Thank you :)

**Comment by PKief** [comment]
@DeanAyalon yeah you're right, the latest version broke it. I've tested it yesterday locally and it worked. The reason is the third party dependency lodash which is not compatible to CSP security checks that Firefox is applying.

![image](https://github.com/user-attachments/assets/ce5d618e-081a-4da8-aa7e-7bcd320c3f72)

I'm going to investigate that issue. I'm not sure where it's coming from as I've removed the dependency from the latest version of the Material Icon Theme upstream repository: https://github.com/material-extensions/vscode-material-icon-theme/releases/tag/v5.5.1.

**Comment by PKief** [comment]
@DeanAyalon for now you can go on https://addons.mozilla.org/en-US/firefox/addon/material-icons-for-github/versions/ and use version v1.8.16 to make it work again (remove the current version before installing the 1.8.16 version).

**Comment by PKief** [comment]
It looks like the package-lock json still had the wrong version of the upstream material icon theme (it should be v5.5.1)
![image](https://github.com/user-attachments/assets/43723171-d0af-40fc-bdec-f947e50a97c2)

I'll update this and it should be working with the next release. I'll let you know once it's fixed!

**Comment by PKief** [comment]
@DeanAyalon it's working now. There's a new 1.8.18 version which can be installed.

**Comment by DeanAyalon** [comment]
Thank you :)
