### ISSUE TITLE
Add support to change the languages icons

### ISSUE THREAD

**Issue by shivapoudel** [material-extensions/material-icons-browser-extension#4]
Add support to configure languages and file associations just like we do in VSCode settings over here?

```
	"material-icon-theme.languages.associations": {
		"php": "php_elephant"
	},
```

Suggestion: Although Chrome extension can be run on Edge but also is there any plan to release it for the MS Edge store!!

**Comment by Claudiohbsantos** [comment]
This looks interesting but to be honest I'll probably keep it in the icebox for a while. This would take significant work in terms of creating a user interface of some sort to expose these settings, and I'm not sure how many people have custom associations like that. Very happy to take PRs for the functionality if anyone wants to jump on it sooner though.

Re: Edge, this is the first request for MS Edge store I get. If there is enough interest in it I'd be happy to look into it, I imagine it must be straightforward. I'm just mindful of adding another store because since updates need to be made manually now, that increases the time that a single update takes, which makes me less likely to do them frequently :p

**Comment by shivapoudel** [comment]
@Claudiohbsantos I am new to browser extension development. So yesterday night I thought why not release a fork of this addon to the MS Edge also. I have give look to the codebase and understand how this extension work. So I think now you can release for the Edge too.

**Comment by shivapoudel** [comment]
@Claudiohbsantos I came with a simple idea let me share it with you, my friend :)

Most of the time we don't require icon pack-specific icons for GitHub for the sake of customization. But since my projects are highly based on React/Redux I used that icon pack. By default the VSCode material icon pack is angular and all our Github icons from this extension are being angular. TBH I have never worked with angular so folder icons are driving me crazy knowing or unknowingly. So to solve this issue let's not focus on a customization options page entirely as I don't think this way would be beneficial for just rendering icons.

Let's implement the simple configuration in the upcoming version:
- Fetch config from `.github-material-icons` or VSCode `settings.json` file and use them to map the icon pack file/folder svg.
- For the first iteration let's just target `activeIconPacks` and on a later run, we go on implementing other settings compatibility.

**Comment by Claudiohbsantos** [comment]
I agree that the simplest solution for configuration here is the best.

**Comment by busybox11** [comment]
Agreed - I'd love language icons to be changed.

For instance, I've got a NestJS app on GH that shows `*.module.ts` files as Angular, even though they're Nest. Got confused at first, kind of defeats the point of the language icons haha.

Addressed here on the OG material icons repo: https://github.com/PKief/vscode-material-icon-theme/issues/503#issuecomment-611126816
