### ISSUE TITLE
Consider a more lenient `engines` req in package.json

### ISSUE THREAD

**Issue by AdamRaichu** [material-extensions/material-icons-browser-extension#79]
As it is right now, package.json has the following values for the `engines` key.

https://github.com/Claudiohbsantos/github-material-icons-extension/blob/32fc7be79485b4c6fd4655700c380feb07114892/package.json#L16-L19

I tried to clone this repo and install by running `npm i`. I received an error telling me that my node and npm versions were not compatible. (I was using node v18.16.0 and npm 9.8.1.)

I believe you should consider changing the engine requirement from `^` (Include everything that does not increment the first non-zero portion of semver) to `>=` (Specify a range of stable versions).

https://semver.npmjs.com/

...**Unless** using a newer version of node would indeed break the repo, in which case I feel like you should mention that somewhere.

**Comment by csandman** [comment]
Haha, this is funny because I thought the same thing a while ago. Once upon a time (before I put up a PR to change it) it was using _exact_ versions. I changed it to this to make it at least a bit more general, but that was a while ago. Tbh, there probably doesn't need to be an `engines` field at all.

**Comment by PKief** [comment]
We've removed the engine configuration for now. So you should be able to run the scripts with Node.js LTS (>=20). No need to have the exact node version on your machine.
