### ISSUE TITLE
Allow users to specify custom domains 

### ISSUE THREAD

**Issue by jamiehaywood** [material-extensions/material-icons-browser-extension#84]
I have an internally hosted GitLab at work, and I would like to be able to specify a custom domain to use the GitLab icon parser.

At first glance at the code, this will probably need a rethink about how URLs are associated to their `providerConfigs` - not sure how you would want to approach that? 

I can give the feature a go if you think it would be worthwhile, sketch out my idea & raise a PR.

**Comment by theoludwig** [comment]
That would be a useful feature for specyfing [Gitea](https://gitea.io) domains as well.
As gitea.com is specified in the default domains, it is supported.

**Comment by theoludwig** [comment]
For reference, I tried to make it work with the minimal code changes as possible, and it only takes 3 lines of code to add our own custom domain (manually). 
Commit: https://github.com/theoludwig/github-material-icons-extension/commit/12d81470e671fb2397293f4ca555a5fb02150819

Of course, it would be better if it was not directly in the source code, hard coded, but rather a User config and also dynamic, so that users can add custom domains indefinitely.
To implement this feature, the tasks could be:
- implement a way to link a custom domain to a provider (e.g: Gitea, GitLab, etc.).
- add UI in `src/ui/settings-popup.html` to add custom domains and link them to providers.
- store the config of custom domains, and correctly load/use it to check if the extension should run.

**Comment by mikeydevelops** [comment]
This is possible now, #85 was merged in the fork and then the fork was merged here. You can close this now.

**Comment by mikeydevelops** [comment]
Latest version is 1.8.18, I do not know when it will release to browser stores, but I presume sometime by the end of the week.

**Comment by PKief** [comment]
Yes, the release should happen as soon as possible. I'm working on this 😊

**Comment by PKief** [comment]
As #85 has been merged with https://github.com/material-extensions/material-icons-browser-extension/commit/0d067d039489b48993355a2362c7bd3b602467dd I'm going to close this issue now.
