### ISSUE TITLE
Nest icon pack is not working

### ISSUE THREAD

**Issue by PedroMidueno** [material-extensions/material-icons-browser-extension#86]
For about a week now the nest icons have not been shown, at first I thought it was because of my internet connection because I had some problems, but now it has been restored and the problem with the icons persists, I have already tried deleting the extension and reinstalling it , but they are not displayed yet.

If it's worth your information, I'm on Google Chrome version 124.0.6367.118

Here's an screenshot showing the issue.

![image](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/146006877/bc545634-fefd-4386-917d-4fe297508043)

And these are my settings.
![image](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/146006877/fcaa1ef9-c5da-4e8f-b13f-73cb9d0d315f)

**Comment by fish-can** [comment]
Since `vscode-material-icon-theme` version 5.1.0 is the last version to include `nest-*.svg` icons, later versions only have `nest.svg`.

![image](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/9313825/4f2024c4-a4d1-4da2-9c8a-55ffde3a22ee)

This project's build script clone from the main branch, which naturally lacks the icons.

![image](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/9313825/29c4c779-47d0-45b0-803b-0bd9bd63ef0d)

![image](https://github.com/Claudiohbsantos/github-material-icons-extension/assets/9313825/5bce6056-27e6-474f-a551-b4a055f252d3)

**Comment by PKief** [comment]
That's right, in version 5.1.0 we've introduced a new clone feature. That means, that we only have one single nest.svg file which is cloned into multiple files:

https://github.com/PKief/vscode-material-icon-theme/blob/main/src%2Ficons%2FfileIcons.ts#L1677

Same applies for folder icons. We did this to give the users more flexibility of creating custom icons and to reduce the amount of svg files.
