### ISSUE TITLE
Firefox manifest is not properly configured

### ISSUE THREAD

**Issue by lumynou5** [material-extensions/material-icons-browser-extension#99]
Firefox manifest is not properly configured and requires access to all data on all domains.

**Comment by mikeydevelops** [comment]
That is intentional, since I couldn't figure a way to ask for permission for each website on firefox. see https://github.com/material-extensions/material-icons-browser-extension/pull/85#issuecomment-2080211036

**Comment by mikeydevelops** [comment]
Currently, Firefox does not support `optional_host_permissions` to allow us to request custom domains, so for Firefox we need access to all websites, because otherwise we would have to add each individual host to the manifest every time someone wants to support their domain and that will not happen.

There are two options from now:
 - We stop supporting custom domains on Firefox, and remove the permission to access all websites from the manifest. That then adds feature disparity between browsers.
 - Keep the permission as is to have feature parity between browsers. And/Or add note to Firefox description page for the extension to explain why access to all websites is needed.

Tagging @vvirtues, because they also disagreed.

**Comment by vvirtues** [comment]
https://support.mozilla.org/en-US/kb/manage-optional-permissions-extensions
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions
shouldn't this do it? idk much about extensions but I think this is what you want

**Comment by vvirtues** [comment]
![image](https://github.com/material-extensions/material-icons-browser-extension/assets/81705406/a4c689f6-bda6-40f8-9795-47d5ef5bfa1a)

**Comment by vvirtues** [comment]
made a pull request im pretty sure should fix it
